version: '3.9'

services:
  ########################
  #    MongoDB
  ########################
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always

  ########################
  #    ClickHouse
  ########################
  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    restart: always

  ########################
  #    App
  ########################
  benchmark:
    build: .
    image: benchmark
    container_name: benchmark
    env_file:
      - .env
    depends_on:
      - mongodb
      - clickhouse
